create table t收費評估表
(f1 int primary key identity(1,1),
 f2 nvarchar(max),
 f3 nvarchar(max),
 f4 nvarchar(max),
 f5 nvarchar(max))

insert into t收費評估表 values
('病史:','姓名:','性別:',NULL),
('床號:','出生日期:','評估者:','日期:'),
('項目','自我照顧能力程度',NULL,NULL),
('1)進食','可自行進食','A',NULL),
(NULL,'需協助進食','B',NULL),
(NULL,'完全需餵食或管灌','C',NULL),
('2)個人清潔','能自行獨立完成梳洗','A',NULL),
(NULL,'需部分協助','B',NULL),
(NULL,'完全依賴','C',NULL),
('3)穿脫衣服','可自行穿脫衣服、鞋子、輔具','A',NULL),
(NULL,'需部分協助','B',NULL),
(NULL,'完全依賴','C',NULL),
('4)上廁所,如廁','可自行進出廁所、完成如廁','A',NULL),
(NULL,'需協助倒尿壺、便盆、並清洗','B',NULL),
(NULL,'失禁換尿布或協助帶至廁所','C',NULL),
('5)洗澡','可自行脫衣服、洗澡','A',NULL),
(NULL,'部分協助、參與洗澡','B',NULL),
(NULL,'完全依賴','C',NULL),
('6)移位,上下床,輪椅,如廁','獨立上下床及輪椅','A',NULL),
(NULL,'需注意與部分協助','B',NULL),
(NULL,'完全依賴','C',NULL),
('7)行走','可獨立行走','A',NULL),
(NULL,'部分需協助','B',NULL),
(NULL,'完全依賴、行走全程配陪伴','C',NULL),
('8)翻身','可自行翻身','A',NULL),
(NULL,'需協助翻身','B',NULL),
(NULL,NULL,NULL,NULL),
('分級標準','一個C以上,照護費為 3000 元',NULL,NULL),
(NULL,'三個B以上無C項者照護費為1500元',NULL,NULL),
(NULL,'二個B以下照護費為0元',NULL,NULL),
('失智者CDR表評估為:',NULL,NULL,NULL),
('1分輕度(30000元)',NULL,NULL,NULL),
('2分中度(35000元)',NULL,NULL,NULL),
('3分重度(40000元)',NULL,NULL,NULL)